from typing import List

from tqdm import tqdm


def _concept_difficulty(c: str, all_concepts: List[str]) -> float:
    import nltk
    distances = [nltk.edit_distance(c, other_c) for other_c in all_concepts if other_c != c]
    return min(distances)


def recompute(qa_train):
    # method only for reproducibility purposes, teabreac_train dataset should not change in time
    all_concepts = qa_train["program_modules_str"].unique()
    concepts_edit_distances = {}
    for c in tqdm(all_concepts, desc="Computing concepts difficulty"):
        concepts_edit_distances[c] = _concept_difficulty(c, all_concepts)


concepts_edit_distances = {'select project filter_a_where_b_is_max project': 2, 'select kth_highest project': 4,
                           'select project grouped_count filter_a_where_b_is_compared_to project project': 8,
                           'select project kth_highest minimum_number arithmetic_subtraction': 8,
                           'select project project filter_a_where_b_is_min project': 2,
                           'select select select count count arithmetic_subtraction': 7,
                           'select filter project select list_subtraction count': 5,
                           'select filter filter arg_intersection list_subtraction project': 10,
                           'select filter project filter_a_where_b_is_min': 2,
                           'select project project project arithmetic_sum_single': 4, 'select select union': 4,
                           'select select project project filter_a_where_b_is_compared_to count': 6,
                           'select project grouped_count filter_a_where_b_is_compared_to': 4,
                           'select project project': 4,
                           'select project filter_a_where_b_is_max project filter union': 6,
                           'select project project union': 4, 'select project project project project': 5,
                           'select filter count count arithmetic_subtraction': 5,
                           'select project project filter union': 5, 'select project select project filter': 4,
                           'select project project filter project union': 5, 'select project kth_highest project': 6,
                           'select project filter_a_where_b_is_compared_to filter union': 5,
                           'select filter count project': 5,
                           'select project count filter_a_where_b_is_compared_to project': 5,
                           'select filter project': 4, 'select minimum_number project project': 2,
                           'select select select filter filter union': 6,
                           'select project filter_a_where_b_is_compared_to_date filter_a_where_b_is_compared_to_date union project': 16,
                           'select project filter_a_where_b_is_compared_to filter list_subtraction': 7,
                           'select project minimum_number project': 2,
                           'select project project filter_a_where_b_is_min_date project': 2,
                           'select filter project union': 5,
                           'select project project filter_a_where_b_is_max list_subtraction project': 8,
                           'select project grouped_count filter_a_where_b_is_max list_subtraction filter_a_where_b_is_max': 4,
                           'select project filter_a_where_b_is_in_range project': 4,
                           'select project project filter list_subtraction': 5,
                           'select minimum_number list_subtraction minimum_number project': 4,
                           'select arithmetic_sum_single project': 8, 'select list_subtraction project count': 5,
                           'select project select list_subtraction project filter_a_where_b_is_compared_to': 14,
                           'select project filter_a_where_b_is_compared_to_date': 5,
                           'select filter project filter_a_where_b_is_compared_to arg_intersection count': 11,
                           'select project select list_subtraction': 4, 'select select intersection select filter': 7,
                           'select select project filter filter': 4,
                           'select filter project filter_a_where_b_is_compared_to_date': 5,
                           'select select project project arithmetic_sum_multiple arithmetic_subtraction': 4,
                           'select filter project select list_subtraction project': 5,
                           'select select count count arithmetic_division': 4,
                           'select select arithmetic_sum_multiple arithmetic_subtraction': 6,
                           'select project count project count arithmetic_subtraction': 6,
                           'select select compare_dates compare_dates arg_bool': 10,
                           'select select compare_numbers compare_numbers arg_bool': 6,
                           'select project filter_a_where_b_is_compared_to': 5,
                           'select project project list_subtraction': 4,
                           'select project filter_a_where_b_is_compared_to project count': 5,
                           'select project grouped_count filter_a_where_b_is_min': 2,
                           'select project filter filter union count': 5, 'select project': 4,
                           'select project filter_a_where_b_is_given_value project project project': 7,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to arg_intersection': 6,
                           'select filter select filter': 4, 'select arithmetic_subtraction': 7,
                           'select project filter grouped_sum filter_a_where_b_is_max': 2,
                           'select filter project filter list_subtraction project': 5,
                           'select project count project count arithmetic_sum_multiple': 8,
                           'select project arithmetic_sum_single': 4,
                           'select project project count arithmetic_division': 5, 'select project grouped_count': 4,
                           'select select union filter filter': 6,
                           'select project filter list_subtraction project union': 6,
                           'select select intersection project project': 6,
                           'select project project project project union': 6,
                           'select project grouped_count filter_a_where_b_is_max project count': 5,
                           'select project filter_a_where_b_is_max list_subtraction project': 8,
                           'select project project filter_a_where_b_is_max filter_a_where_b_is_given_value project': 8,
                           'select filter filter count count arithmetic_subtraction': 6,
                           'select project maximum_number filter_a_where_b_is_compared_to project': 11,
                           'select project grouped_count filter_a_where_b_is_max project': 2,
                           'select filter project select list_subtraction': 4,
                           'select filter filter boolean boolean arg_bool': 6,
                           'select project filter filter union project': 5,
                           'select project select project arg_minimum_date': 7,
                           'select project select project arithmetic_mean_single arithmetic_subtraction': 11,
                           'select select are_items_different': 8, 'select project minimum_number': 2,
                           'select project list_subtraction': 4, 'select filter project filter project union': 6,
                           'select project filter_a_where_b_is_given_value list_subtraction project': 5,
                           'select filter filter arg_intersection project': 5, 'select project project union filter': 6,
                           'select filter select project union': 4,
                           'select project project filter_a_where_b_is_max list_subtraction filter_a_where_b_is_max': 6,
                           'select project project filter_a_where_b_is_max project': 2,
                           'select select arithmetic_sum_single arithmetic_sum_single arithmetic_sum_multiple': 8,
                           'select maximum_number project': 2,
                           'select project project filter_a_where_b_is_compared_to count': 4,
                           'select project grouped_mean filter_a_where_b_is_compared_to project': 4,
                           'select arithmetic_sum_single arithmetic_division': 8,
                           'select project arithmetic_mean_single project project': 16, 'select filter filter': 5,
                           'select project filter_a_where_b_is_max project project union': 2,
                           'select select list_subtraction arithmetic_sum_single arithmetic_sum_single arithmetic_subtraction': 17,
                           'select project filter_a_where_b_is_compared_to project filter union': 6,
                           'select project project arithmetic_mean_single filter_a_where_b_is_compared_to project': 8,
                           'select select': 4, 'select filter filter union': 5,
                           'select project filter_a_where_b_is_compared_to project project arithmetic_sum_single': 4,
                           'select filter filter filter arg_intersection project': 6,
                           'select select maximum_number arithmetic_subtraction': 2,
                           'select project filter_a_where_b_is_compared_to list_subtraction count': 6,
                           'select select filter project minimum_date': 9, 'select project select project union': 4,
                           'select project maximum_number list_subtraction maximum_number filter_a_where_b_is_given_value': 4,
                           'select project filter_a_where_b_is_given_value count count arithmetic_subtraction': 20,
                           'select project select project are_items_same': 8, 'select filter project project': 5,
                           'select select arithmetic_subtraction': 4,
                           'select project filter_a_where_b_is_compared_to project project project': 5,
                           'select select arithmetic_sum_single arithmetic_sum_single arg_maximum_number': 2,
                           'select maximum_number select arithmetic_subtraction': 2,
                           'select project filter project project': 5,
                           'select filter filter list_subtraction list_subtraction count': 5,
                           'select project filter filter project': 4, 'select count select count arg_maximum_number': 2,
                           'select project filter project filter_a_where_b_is_compared_to union': 6,
                           'select filter filter project arithmetic_subtraction': 6,
                           'select select arithmetic_sum_single arithmetic_subtraction arithmetic_subtraction': 8,
                           'select project grouped_count arithmetic_mean_single': 4,
                           'select project select intersection': 4, 'select project project maximum_number project': 6,
                           'select project filter_a_where_b_is_compared_to project': 5,
                           'select project minimum_number list_subtraction minimum_number arithmetic_sum_multiple': 4,
                           'select project filter_a_where_b_is_compared_to project project union': 5,
                           'select project maximum_number list_subtraction maximum_number arithmetic_subtraction': 8,
                           'select count project': 5,
                           'select project grouped_count filter_a_where_b_is_compared_to project': 4,
                           'select project project count count arithmetic_subtraction': 6,
                           'select project filter_a_where_b_is_compared_to filter list_subtraction project': 8,
                           'select filter maximum_number project': 2,
                           'select project filter project arithmetic_mean_single': 4,
                           'select project project filter_a_where_b_is_given_value project union': 6,
                           'select project project project arithmetic_sum_multiple': 4, 'boolean project project': 5,
                           'select project project project filter': 4,
                           'select project filter_a_where_b_is_given_value project count': 5,
                           'select filter project filter_a_where_b_is_max project': 2,
                           'select filter filter union project arithmetic_mean_single': 6, 'select filter select': 4,
                           'select project project filter project count': 5,
                           'select project project select list_subtraction': 4,
                           'select select select select select arithmetic_sum_multiple': 7,
                           'select project filter_a_where_b_is_compared_to count': 5,
                           'select filter project filter union project': 6,
                           'select project filter maximum_number minimum_number arithmetic_subtraction': 4,
                           'select list_subtraction': 6, 'select filter filter union project project': 6,
                           'select project project filter project': 4,
                           'select project filter_a_where_b_is_min project project union': 2,
                           'select project grouped_sum filter_a_where_b_is_min': 2,
                           'select project project project project arithmetic_subtraction': 4,
                           'select minimum_number select minimum_number arithmetic_sum_multiple': 8,
                           'select project project grouped_count arithmetic_sum_single': 6,
                           'select project project select list_subtraction project': 5,
                           'select project project project union': 4, 'select project filter list_subtraction': 5,
                           'select kth_lowest': 4, 'select project grouped_mean': 4,
                           'select select project project maximum_number arithmetic_subtraction': 2,
                           'select project filter_a_where_b_is_in_range project project union': 4,
                           'select select filter project': 4, 'select project select project project intersection': 7,
                           'select filter filter count count arithmetic_sum_multiple': 8,
                           'select project grouped_count filter_a_where_b_is_min project union': 6,
                           'select filter filter union project grouped_sum': 8,
                           'select project arithmetic_mean_single filter_a_where_b_is_compared_to': 6,
                           'select project boolean': 5, 'select filter project list_subtraction count': 6,
                           'select project grouped_count filter': 4,
                           'select project project filter_a_where_b_is_compared_to': 4,
                           'select project filter project grouped_count arithmetic_mean_single': 4,
                           'select select filter select filter': 4,
                           'select project filter_a_where_b_is_given_value project filter': 6,
                           'select project project grouped_count filter_a_where_b_is_min project': 2,
                           'select filter filter project arithmetic_sum_single': 4,
                           'select filter filter list_subtraction project': 5,
                           'select project list_subtraction project union': 6,
                           'select filter filter project project intersection': 8,
                           'select select select arithmetic_sum_multiple arithmetic_sum_multiple': 8,
                           'select project filter project count': 5, 'select project filter_a_where_b_is_in_range': 5,
                           'select filter select filter union': 5, 'select filter filter list_subtraction': 6,
                           'select project filter_a_where_b_is_given_value project filter_a_where_b_is_given_value': 8,
                           'select select filter filter project union': 6,
                           'select project filter arithmetic_sum_single': 4, 'select filter list_subtraction count': 5,
                           'select project filter_a_where_b_is_in_range_date project project': 8,
                           'select filter filter filter union project': 5, 'select select arg_maximum_date': 2,
                           'select project filter filter arg_intersection': 6,
                           'select filter list_subtraction project project union': 6,
                           'select project filter_a_where_b_is_given_value': 6,
                           'select project filter_a_where_b_is_compared_to list_subtraction': 6,
                           'select filter project project project arithmetic_sum_single': 7,
                           'select project filter_a_where_b_is_compared_to project project count': 5,
                           'select filter filter arithmetic_sum_single arithmetic_sum_single arithmetic_subtraction': 10,
                           'select project filter filter_a_where_b_is_min project': 2,
                           'select project project union project': 6,
                           'select project maximum_number minimum_number arithmetic_subtraction': 4,
                           'select filter project arithmetic_mean_single': 4,
                           'select project arithmetic_mean_single grouped_mean filter_a_where_b_is_compared_to project': 13,
                           'select project grouped_mean filter_a_where_b_is_max': 2,
                           'select project project minimum_number maximum_number arithmetic_subtraction': 4,
                           'select project select project arg_maximum_number': 4,
                           'select maximum_number arithmetic_subtraction': 7, 'select select select filter filter': 4,
                           'select project union': 4, 'select filter project minimum_number': 2,
                           'select project project union arithmetic_sum_single': 6,
                           'select project project intersection': 4,
                           'select select count count arithmetic_sum_multiple': 6,
                           'select project select project filter_a_where_b_is_given_value': 4,
                           'select arithmetic_mean_single select arithmetic_mean_single arg_maximum_number': 2,
                           'select project filter_a_where_b_is_compared_to project filter project': 6,
                           'select project select grouped_count count filter_a_where_b_is_compared_to': 10,
                           'select select project project intersection': 4,
                           'select project project filter_a_where_b_is_compared_to_date count': 5,
                           'select filter filter filter arg_intersection union': 6,
                           'select project project maximum_number minimum_number arithmetic_subtraction': 4,
                           'select project filter_a_where_b_is_compared_to filter arg_intersection project': 10,
                           'select filter minimum_number': 2,
                           'select project project filter_a_where_b_is_max_date project': 2,
                           'select list_subtraction select list_subtraction': 4,
                           'select filter project arithmetic_subtraction': 5,
                           'select project grouped_count filter project': 8,
                           'select project filter_a_where_b_is_compared_to project arithmetic_sum_single': 4,
                           'select project filter_a_where_b_is_min project project': 2,
                           'select select maximum_number select maximum_number arithmetic_subtraction': 7,
                           'select filter project filter project': 4, 'select filter filter union filter filter': 7,
                           'select project project arithmetic_multiplication': 7,
                           'select project kth_highest kth_lowest arithmetic_subtraction': 4,
                           'select select project': 4, 'select select are_items_same': 8,
                           'select filter project filter_a_where_b_is_compared_to project': 5,
                           'select project select project intersection': 4,
                           'select project filter_a_where_b_is_max project project arithmetic_mean_single': 9,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to project': 5,
                           'select filter boolean': 5,
                           'select project grouped_sum filter_a_where_b_is_compared_to project': 4,
                           'select project filter_a_where_b_is_max project union': 5,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to arg_intersection project': 5,
                           'select project project arithmetic_sum_multiple': 6, 'select select select union filter': 6,
                           'select filter list_subtraction project select arithmetic_subtraction': 10,
                           'select filter minimum_number project': 2,
                           'select maximum_number kth_highest arithmetic_subtraction': 8,
                           'select filter project filter_a_where_b_is_given_value project': 5,
                           'select project project project maximum_date': 5,
                           'select project project count count arg_minimum_number': 2,
                           'select project filter project project count': 5, 'select filter filter filter union': 5,
                           'select select count count compare_numbers': 10, 'select filter filter union project': 5,
                           'select project filter_a_where_b_is_max_date': 5, 'select filter filter project boolean': 5,
                           'select filter filter project union': 5,
                           'select project filter_a_where_b_is_given_value project project': 5,
                           'select project project filter_a_where_b_is_max': 2,
                           'select select arg_minimum_date project': 7,
                           'select maximum_number minimum_number arithmetic_subtraction': 4,
                           'select project filter_a_where_b_is_in_range count': 5, 'select project filter project': 4,
                           'select select maximum_number maximum_number arithmetic_subtraction': 2,
                           'select maximum_number list_subtraction maximum_number arithmetic_subtraction': 8,
                           'select project select filter project': 4,
                           'select project filter list_subtraction arithmetic_sum_single': 8,
                           'select select project filter_a_where_b_is_compared_to count': 4,
                           'select filter select project filter': 4,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to': 6,
                           'select select project project union': 4, 'select select list_subtraction project filter': 7,
                           'select project filter_a_where_b_is_compared_to project project': 5,
                           'select maximum_number project project': 2, 'select filter project project project union': 6,
                           'select project project grouped_mean filter_a_where_b_is_max': 4,
                           'select project project project minimum_number': 2,
                           'select minimum_number select minimum_number arithmetic_subtraction': 2,
                           'select filter filter union count': 5, 'select compare_numbers compare_numbers arg_bool': 7,
                           'select project select filter_a_where_b_is_compared_to count': 4,
                           'select select filter filter union': 4,
                           'select select arithmetic_mean_single arithmetic_mean_single arg_maximum_number': 8,
                           'select select arithmetic_division arithmetic_subtraction arithmetic_subtraction': 8,
                           'select project filter_a_where_b_is_max': 2, 'select select list_subtraction project': 4,
                           'select filter': 5,
                           'select project project arithmetic_sum_multiple arithmetic_subtraction': 6,
                           'select filter list_subtraction project project': 6,
                           'select select select arithmetic_sum_multiple arithmetic_subtraction': 7,
                           'select filter project project union': 4,
                           'select select arithmetic_sum_single arithmetic_sum_single arithmetic_subtraction': 8,
                           'select project project grouped_count filter_a_where_b_is_min': 2,
                           'select project filter_a_where_b_is_given_value filter': 6,
                           'select select select arithmetic_sum_multiple arg_maximum_number': 2,
                           'select project filter_a_where_b_is_given_value filter_a_where_b_is_given_value union project': 5,
                           'select filter project project grouped_mean': 7,
                           'select project filter_a_where_b_is_max filter_a_where_b_is_min union': 10,
                           'select project filter count arithmetic_division': 6,
                           'select project filter_a_where_b_is_compared_to filter project': 5,
                           'select project project grouped_count filter project': 8,
                           'select project project union project count': 6,
                           'select project filter_a_where_b_is_compared_to_date project': 5,
                           'select select count count arithmetic_subtraction': 5,
                           'select project project select list_subtraction count': 5,
                           'select filter list_subtraction project arithmetic_mean_single': 4,
                           'select arithmetic_sum_single select arithmetic_sum_single arg_minimum_number': 2,
                           'select filter project filter_a_where_b_is_compared_to union project': 6,
                           'select filter filter list_subtraction arg_intersection project': 10,
                           'select project filter_a_where_b_is_min project': 2,
                           'select select minimum_number arithmetic_subtraction': 2,
                           'select project arithmetic_mean_single filter_a_where_b_is_compared_to project count': 5,
                           'select project filter_a_where_b_is_min project project project': 2,
                           'select minimum_number project': 2, 'select project project filter_a_where_b_is_in_range': 6,
                           'select select list_subtraction': 4, 'select select boolean boolean logical_and': 10,
                           'select project project grouped_sum filter_a_where_b_is_max project': 4,
                           'select select maximum_number minimum_number arithmetic_subtraction': 2,
                           'select filter filter list_subtraction count': 5,
                           'select project project filter_a_where_b_is_max filter_a_where_b_is_max union': 10,
                           'select project project project filter count': 5, 'select project filter': 4,
                           'select project filter project union': 5,
                           'select project filter_a_where_b_is_max list_subtraction project filter_a_where_b_is_max': 4,
                           'select filter project maximum_number project': 6, 'select select filter': 4,
                           'select project select count count arithmetic_division': 7,
                           'select project project project project date_subtraction': 4,
                           'select project filter_a_where_b_is_max project count': 5, 'select project minimum_date': 2,
                           'select project filter list_subtraction project': 5,
                           'select project filter_a_where_b_is_compared_to filter count': 5,
                           'select project select list_subtraction project': 5,
                           'select project maximum_date project': 2,
                           'select project filter_a_where_b_is_max_date project project union': 2,
                           'select project filter_a_where_b_is_min_date project project union': 2, 'select boolean': 5,
                           'select project arithmetic_mean_single filter_a_where_b_is_compared_to project project': 5,
                           'select select filter list_subtraction project project': 7,
                           'select filter maximum_number': 2,
                           'select project project project arithmetic_mean_single': 4,
                           'select select select union project': 6, 'select filter filter filter union filter': 6,
                           'select project filter_a_where_b_is_max project project project': 2,
                           'select filter list_subtraction project union': 6, 'select project project select filter': 4,
                           'select select arithmetic_sum_single maximum_number arithmetic_subtraction': 12,
                           'select project grouped_mean arithmetic_mean_single filter_a_where_b_is_compared_to project': 4,
                           'select project filter filter union': 4,
                           'select project filter_a_where_b_is_given_value project project union': 6,
                           'select project filter_a_where_b_is_given_value count': 5,
                           'select project kth_highest kth_highest arithmetic_subtraction': 4,
                           'select project filter filter list_subtraction union': 7,
                           'select project grouped_count filter_a_where_b_is_max': 2,
                           'select filter list_subtraction project grouped_mean': 9,
                           'select project project count count arg_maximum_number': 2,
                           'select project grouped_count filter_a_where_b_is_compared_to count': 5,
                           'select project project count': 5,
                           'select project arithmetic_mean_single filter_a_where_b_is_compared_to project': 5,
                           'select list_subtraction filter': 6,
                           'select project grouped_sum arithmetic_mean_single filter_a_where_b_is_compared_to project': 4,
                           'select select intersection project': 5, 'select project select arithmetic_subtraction': 4,
                           'select maximum_number minimum_number project project arithmetic_subtraction': 4,
                           'select list_subtraction project project': 5,
                           'select project grouped_sum filter_a_where_b_is_max project': 4,
                           'select project select filter': 4,
                           'select project filter_a_where_b_is_compared_to_date count': 5,
                           'select count select count arithmetic_subtraction': 4,
                           'select select arithmetic_sum_multiple': 6,
                           'select arithmetic_sum_single select arithmetic_subtraction': 7,
                           'select project project date_subtraction': 4, 'select maximum_number': 2,
                           'select filter project filter filter arg_intersection': 6, 'select select union project': 6,
                           'select select project project minimum_number arithmetic_subtraction': 2,
                           'select filter filter arg_intersection project arithmetic_sum_single': 4,
                           'select project project grouped_count': 4,
                           'select project filter_a_where_b_is_compared_to filter union project': 6,
                           'select filter filter project': 5, 'select project count project': 5,
                           'select filter kth_highest project': 6,
                           'select maximum_number list_subtraction maximum_number project': 4,
                           'select project filter_a_where_b_is_min filter union': 8,
                           'select project project filter_a_where_b_is_compared_to_date': 5,
                           'select project filter project filter_a_where_b_is_compared_to arg_intersection': 9,
                           'select project maximum_number': 2,
                           'select filter project filter_a_where_b_is_compared_to filter union': 7,
                           'select project filter project project union': 4,
                           'select select arithmetic_mean_single arithmetic_mean_single arithmetic_subtraction': 8,
                           'select project grouped_sum': 4, 'select project filter_a_where_b_is_max_date project': 2,
                           'select project project count count arithmetic_sum_multiple': 8,
                           'select project filter list_subtraction project arithmetic_sum_single': 8,
                           'select filter filter arg_intersection': 6, 'select project kth_lowest': 4,
                           'select project minimum_number project project': 8,
                           'select arithmetic_sum_single select arithmetic_sum_single arithmetic_subtraction': 8,
                           'select maximum_number list_subtraction arithmetic_mean_single': 2,
                           'select filter filter arithmetic_mean_single arithmetic_mean_single arg_maximum_number': 8,
                           'select project filter_a_where_b_is_given_value filter project': 6,
                           'select project filter filter_a_where_b_is_compared_to arg_intersection project': 14,
                           'select select date_subtraction': 4, 'select project filter_a_where_b_is_in_range_date': 5,
                           'select project boolean boolean arg_bool': 4, 'select project filter grouped_sum': 4,
                           'select project minimum_date project': 2, 'select project project filter filter union': 6,
                           'select project project project arithmetic_subtraction': 4,
                           'select project grouped_count filter_a_where_b_is_given_value': 7,
                           'select project grouped_mean filter_a_where_b_is_compared_to': 4,
                           'select project minimum_number maximum_number arithmetic_subtraction': 4,
                           'select filter filter filter union count': 5, 'select project grouped_sum filter': 4,
                           'select kth_lowest project': 2,
                           'select select intersection project filter_a_where_b_is_max': 9,
                           'select project project minimum_date': 2, 'boolean boolean boolean arg_bool': 5,
                           'select project count filter count arithmetic_subtraction': 5,
                           'select filter project project list_subtraction': 4,
                           'select project filter filter project arithmetic_subtraction': 5,
                           'select filter list_subtraction': 5, 'select select project list_subtraction': 4,
                           'select select intersection project filter project': 7,
                           'select project filter project project project': 5,
                           'select select union project project union': 6,
                           'select filter project project arithmetic_mean_single': 4,
                           'select filter project filter project project': 6,
                           'select kth_highest minimum_number project project arithmetic_subtraction': 13,
                           'boolean boolean logical_and': 3,
                           'select project project project project arithmetic_sum_multiple': 8,
                           'select project filter_a_where_b_is_given_value project': 5,
                           'select select count arithmetic_subtraction': 5, 'select project maximum_number project': 2,
                           'select project filter_a_where_b_is_compared_to_date filter': 5,
                           'select filter filter project count': 5,
                           'select project project project list_subtraction': 4,
                           'select project filter_a_where_b_is_given_value project arithmetic_mean_single': 8,
                           'select list_subtraction project': 5,
                           'select project filter filter arg_intersection count': 5,
                           'select project project arithmetic_subtraction project': 8,
                           'select project filter project filter_a_where_b_is_max': 2, 'select minimum_number': 2,
                           'select select filter project project union': 4, 'select project project minimum_number': 2,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to list_subtraction project': 10,
                           'select project filter project minimum_number': 2, 'select filter filter project project': 5,
                           'select project project project maximum_number': 2,
                           'select filter project project arithmetic_sum_single': 4,
                           'select boolean boolean arg_bool': 5,
                           'select project filter count count arithmetic_subtraction': 6,
                           'select project grouped_count filter_a_where_b_is_min project': 2,
                           'select project arithmetic_subtraction project': 8,
                           'select project project grouped_count filter': 7,
                           'select filter project filter filter union': 6, 'select select count arithmetic_division': 5,
                           'select filter filter project list_subtraction': 6,
                           'select project arithmetic_sum_single project count arithmetic_subtraction': 6,
                           'select project filter_a_where_b_is_given_value project grouped_count': 8,
                           'select project project arithmetic_mean_single arithmetic_mean_single arithmetic_subtraction': 8,
                           'select select arithmetic_sum_single arithmetic_sum_single arg_minimum_number': 2,
                           'select filter filter filter': 5,
                           'select project project filter_a_where_b_is_compared_to project': 5,
                           'select project grouped_count filter_a_where_b_is_max filter_a_where_b_is_given_value project': 8,
                           'select project project project project arg_minimum_date': 5,
                           'select project maximum_number minimum_number arithmetic_sum_multiple': 6,
                           'select project project filter count': 5,
                           'select select project project date_subtraction': 7,
                           'select project filter_a_where_b_is_compared_to list_subtraction project arithmetic_mean_single': 14,
                           'select select project project arithmetic_subtraction': 4,
                           'select filter list_subtraction project': 5, 'select project project arg_maximum_number': 2,
                           'select project count arithmetic_division arithmetic_subtraction': 13,
                           'select project project filter project arithmetic_subtraction': 4,
                           'select select arg_minimum_number': 2,
                           'select select arithmetic_sum_single arithmetic_subtraction': 6,
                           'select select filter filter': 4, 'select select compare_numbers': 5,
                           'select project project arithmetic_sum_single': 4, 'select filter project maximum_number': 2,
                           'select project minimum_number list_subtraction minimum_number filter_a_where_b_is_given_value': 4,
                           'select select project filter': 4, 'select project maximum_date': 2,
                           'select project filter_a_where_b_is_given_value list_subtraction': 6,
                           'select project grouped_sum filter_a_where_b_is_compared_to': 4,
                           'select project filter_a_where_b_is_in_range_date project': 5,
                           'select minimum_number select arithmetic_subtraction': 2,
                           'select filter project arithmetic_sum_single': 4,
                           'select filter filter arithmetic_sum_single': 4, 'select select intersection filter': 6,
                           'select project filter_a_where_b_is_max filter union project': 9,
                           'select select count count arg_maximum_number project': 8, 'select filter count': 5,
                           'select project filter grouped_sum filter_a_where_b_is_max project': 4,
                           'select project filter filter_a_where_b_is_max': 2,
                           'select filter list_subtraction filter union': 6, 'select select intersection': 6,
                           'select project filter project filter': 4,
                           'select project project project filter_a_where_b_is_min': 2,
                           'select project project project arithmetic_sum_multiple arithmetic_subtraction': 4,
                           'select select count count arg_maximum_number': 2,
                           'select project filter_a_where_b_is_compared_to project arithmetic_mean_single': 4,
                           'select project filter_a_where_b_is_compared_to project grouped_sum arithmetic_mean_single': 8,
                           'select project project filter_a_where_b_is_given_value project': 5, 'select count': 5,
                           'select project project project arithmetic_sum_multiple arithmetic_sum_multiple': 8,
                           'select project count count arithmetic_division': 4,
                           'select count select count arithmetic_subtraction project': 8,
                           'select project grouped_sum filter_a_where_b_is_max': 2, 'select project filter boolean': 5,
                           'select maximum_date': 5,
                           'select project filter_a_where_b_is_min list_subtraction project filter_a_where_b_is_min': 4,
                           'select select project project filter_a_where_b_is_compared_to': 4,
                           'select project grouped_count arithmetic_sum_single': 4,
                           'select project project project filter union': 5,
                           'select project arithmetic_mean_single filter_a_where_b_is_compared_to count': 5,
                           'select project project grouped_count filter_a_where_b_is_max': 2,
                           'select project filter_a_where_b_is_given_value filter_a_where_b_is_given_value union count': 5,
                           'select project grouped_count filter_a_where_b_is_min project project': 2,
                           'select project filter_a_where_b_is_min boolean': 5,
                           'select filter project filter_a_where_b_is_compared_to': 5,
                           'select maximum_number list_subtraction maximum_number list_subtraction maximum_number': 23,
                           'select project project project filter project': 4,
                           'select project list_subtraction count': 4,
                           'select project filter list_subtraction count': 5,
                           'select select arithmetic_subtraction arithmetic_subtraction': 8,
                           'select filter filter project maximum_number': 2,
                           'select project project project union project': 4,
                           'select count filter count arithmetic_subtraction': 5, 'select select compare_dates': 5,
                           'select project project filter_a_where_b_is_max list_subtraction': 8,
                           'select project filter maximum_number': 6,
                           'select select project project intersection project': 6,
                           'select project filter project filter union': 6,
                           'select project select project project filter_a_where_b_is_compared_to': 7,
                           'select project select filter project arithmetic_subtraction': 4,
                           'select select project project arithmetic_sum_multiple': 4,
                           'select project filter_a_where_b_is_given_value filter_a_where_b_is_compared_to union count': 11,
                           'select project project project': 5,
                           'select project filter_a_where_b_is_min project arithmetic_sum_single': 10,
                           'select project maximum_date select project date_subtraction': 11,
                           'select select filter count': 4, 'select project project grouped_sum': 4,
                           'select kth_highest kth_lowest arithmetic_subtraction': 8,
                           'select filter filter filter arg_intersection': 6,
                           'select filter filter project grouped_count': 7, 'select filter project project filter': 4,
                           'select project filter filter_a_where_b_is_compared_to': 5,
                           'select filter select filter project': 4,
                           'select project project filter_a_where_b_is_given_value count': 5,
                           'select minimum_number maximum_number project project arithmetic_subtraction': 4,
                           'select project maximum_number kth_highest arithmetic_subtraction': 4,
                           'select project select filter_a_where_b_is_compared_to': 4,
                           'select filter filter project arithmetic_mean_single': 4,
                           'select project filter_a_where_b_is_given_value list_subtraction count': 5,
                           'select filter project grouped_count': 6,
                           'select filter filter list_subtraction list_subtraction project': 5,
                           'select project project filter list_subtraction count': 5,
                           'select filter project filter_a_where_b_is_max': 2,
                           'select select project filter_a_where_b_is_given_value project are_items_same': 17,
                           'select project select filter filter': 4, 'select project count select project count': 9,
                           'select project project project filter_a_where_b_is_given_value': 4,
                           'select select project project filter': 4,
                           'select maximum_number minimum_number arithmetic_sum_multiple': 8,
                           'select select project project arg_minimum_number': 2,
                           'select project project arithmetic_sum_single arithmetic_subtraction': 6,
                           'select minimum_number maximum_number arithmetic_subtraction': 4,
                           'select select arithmetic_sum_multiple select arithmetic_subtraction': 7,
                           'select project arithmetic_subtraction': 4, 'select project project boolean': 5,
                           'select list_subtraction project list_subtraction': 4,
                           'select project filter filter_a_where_b_is_max project': 2,
                           'select project select project arithmetic_subtraction': 4,
                           'select project filter_a_where_b_is_min_date project': 2,
                           'select project project maximum_date': 2, 'select filter arithmetic_mean_single': 4,
                           'select project project filter_a_where_b_is_compared_to project grouped_mean': 4,
                           'select project kth_highest': 4, 'select filter project filter count': 5,
                           'select filter filter project project union': 5,
                           'select maximum_number select project filter_a_where_b_is_compared_to count': 14,
                           'select project project project filter_a_where_b_is_max': 2,
                           'select select filter filter project': 4, 'select select list_subtraction count': 4,
                           'select filter project project filter_a_where_b_is_given_value': 6,
                           'select project project minimum_number list_subtraction arithmetic_mean_single': 10,
                           'select project select list_subtraction count': 5,
                           'select filter project filter_a_where_b_is_compared_to project arithmetic_subtraction': 7,
                           'select project arithmetic_sum_single select arithmetic_sum_single arithmetic_subtraction': 4,
                           'select project project filter': 4, 'select filter filter project minimum_number': 2,
                           'select select minimum_number minimum_number arithmetic_subtraction': 2,
                           'select count project project': 5, 'select project filter project arithmetic_sum_single': 4,
                           'select project filter_a_where_b_is_compared_to project project arithmetic_mean_single': 4,
                           'select filter project maximum_number minimum_number arithmetic_subtraction': 6,
                           'select project filter filter': 4,
                           'select maximum_number select maximum_number arithmetic_subtraction': 2,
                           'select kth_lowest minimum_number arithmetic_subtraction': 4,
                           'select project arithmetic_sum_single project arithmetic_subtraction': 6,
                           'select select date_subtraction project': 4, 'select project filter select filter': 4,
                           'select project project arg_minimum_number': 2,
                           'select project maximum_number list_subtraction maximum_number': 4,
                           'select select project project filter project': 4,
                           'select project filter_a_where_b_is_max list_subtraction filter_a_where_b_is_max project': 12,
                           'select project project filter_a_where_b_is_max project union': 6,
                           'select select select arithmetic_sum_multiple': 5, 'select k_lowest project': 2,
                           'select select count arithmetic_sum_multiple': 5,
                           'select project filter_a_where_b_is_min': 2,
                           'select filter filter arg_intersection project project': 6,
                           'select select arg_maximum_number project': 7,
                           'select project project select project date_subtraction': 4,
                           'select project project grouped_mean filter_a_where_b_is_max project': 4,
                           'select project project maximum_number kth_highest arithmetic_subtraction': 8,
                           'select project project kth_highest': 8,
                           'select filter list_subtraction count count arithmetic_subtraction': 10,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to arg_intersection count': 5,
                           'select project project project arg_minimum_number': 2,
                           'select project project project project arg_maximum_number': 2,
                           'select filter project filter_a_where_b_is_in_range count': 6,
                           'select count select arithmetic_subtraction': 5,
                           'select project select project filter_a_where_b_is_compared_to': 4,
                           'select filter project project project project': 6,
                           'select project arithmetic_sum_single project arithmetic_sum_single arithmetic_subtraction': 4,
                           'select project grouped_count maximum_number': 8,
                           'select maximum_number minimum_number project project intersection': 12,
                           'select filter project arithmetic_mean_single project filter_a_where_b_is_compared_to': 15,
                           'select filter filter union filter': 6,
                           'select project grouped_count filter_a_where_b_is_min count': 5,
                           'select filter filter arg_intersection count': 5, 'select filter filter minimum_number': 6,
                           'select list_subtraction count': 5, 'select project grouped_count filter project project': 8,
                           'select project project filter filter': 4, 'select project filter count': 4,
                           'select project project arg_intersection project': 11, 'boolean boolean are_items_same': 10,
                           'select filter project project project': 6,
                           'select project select project arithmetic_sum_multiple': 4,
                           'select filter project filter_a_where_b_is_compared_to_date union count': 10,
                           'select filter project filter_a_where_b_is_compared_to union': 5,
                           'select project maximum_number list_subtraction arithmetic_mean_single': 8,
                           'select select count count are_items_same': 10, 'select select project union': 4,
                           'select minimum_number list_subtraction arithmetic_mean_single': 2,
                           'select project select union': 4,
                           'select project kth_lowest filter_a_where_b_is_given_value': 4,
                           'select select project arithmetic_division': 5,
                           'select project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to count': 5,
                           'select select arithmetic_subtraction arithmetic_division arithmetic_subtraction': 16,
                           'select project filter_a_where_b_is_max boolean boolean arg_bool': 10,
                           'select project project filter_a_where_b_is_min': 2,
                           'select project filter_a_where_b_is_compared_to_date project filter': 7,
                           'select project select filter_a_where_b_is_given_value': 4,
                           'select select arg_minimum_date': 2, 'select project project arithmetic_subtraction': 4,
                           'select filter filter arithmetic_sum_single arithmetic_sum_single arg_maximum_number': 2,
                           'select project filter_a_where_b_is_compared_to project filter arg_intersection': 12,
                           'select project project project count': 5, 'select select select arg_maximum_number': 2,
                           'select project select project project arithmetic_subtraction': 4,
                           'select project filter project maximum_number': 2,
                           'select filter filter project project boolean': 6,
                           'select arithmetic_mean_single select arithmetic_mean_single arithmetic_subtraction': 8,
                           'select arithmetic_mean_single': 4,
                           'select project project filter_a_where_b_is_given_value': 4,
                           'select project project filter filter arg_intersection': 6,
                           'select project project grouped_sum filter_a_where_b_is_max': 4,
                           'select project project arithmetic_mean_single': 4, 'select arithmetic_sum_single': 4,
                           'select filter project project filter_a_where_b_is_max': 6,
                           'select project count compare_numbers': 9,
                           'select filter project select arithmetic_subtraction': 7,
                           'select filter filter count count arg_minimum_number': 2,
                           'select select project project arg_minimum_date': 2,
                           'select project maximum_number kth_lowest arithmetic_subtraction': 4,
                           'select filter project filter_a_where_b_is_min project': 2,
                           'select project maximum_number list_subtraction maximum_number arithmetic_sum_multiple': 4,
                           'select project grouped_count arithmetic_mean_single filter_a_where_b_is_compared_to project': 4,
                           'select filter project maximum_date project count': 7,
                           'select select union maximum_number': 6, 'select project project maximum_number': 2,
                           'select project grouped_mean filter_a_where_b_is_max list_subtraction filter_a_where_b_is_max': 4,
                           'select select project project arg_maximum_number': 2,
                           'select kth_highest minimum_number arithmetic_subtraction': 4,
                           'select project project boolean boolean arg_bool': 5,
                           'select project filter_a_where_b_is_max project project': 2,
                           'select project filter filter boolean': 5, 'select select boolean boolean arg_bool': 4,
                           'select project project minimum_date project count': 8,
                           'select project filter grouped_count arithmetic_sum_single': 6,
                           'select project maximum_number arithmetic_subtraction': 4,
                           'select project boolean boolean boolean arg_bool': 5,
                           'select filter filter project project arithmetic_sum_multiple': 8,
                           'select filter list_subtraction project arithmetic_sum_single': 4,
                           'select project filter_a_where_b_is_min list_subtraction filter_a_where_b_is_min': 8,
                           'select project project project intersection': 4,
                           'select project project arg_minimum_date': 2,
                           'select project project project arg_maximum_number': 2,
                           'select count select count arithmetic_sum_multiple': 6,
                           'select project filter grouped_count': 4,
                           'select count project arithmetic_sum_single arithmetic_division': 13,
                           'select project filter project filter_a_where_b_is_max arg_intersection': 9,
                           'select select compare_numbers compare_numbers logical_and': 10,
                           'select filter filter arg_intersection project arithmetic_mean_single': 4,
                           'select select select select arithmetic_sum_multiple arithmetic_subtraction': 7,
                           'boolean boolean arg_bool': 7, 'select project project grouped_mean': 4,
                           'select project filter project project maximum_date': 7,
                           'select filter arithmetic_sum_single': 4,
                           'select project project filter_a_where_b_is_in_range count': 6,
                           'select project project filter project project': 5,
                           'select filter project grouped_count arithmetic_mean_single': 4,
                           'select project filter filter arg_intersection project': 5,
                           'select filter project filter_a_where_b_is_given_value': 6,
                           'select project kth_highest filter_a_where_b_is_given_value': 4,
                           'select filter project list_subtraction': 5,
                           'select select select select arithmetic_sum_multiple': 7,
                           'select project filter filter_a_where_b_is_min project project': 7,
                           'select project grouped_count filter_a_where_b_is_given_value project': 8,
                           'select project filter filter count': 5,
                           'select select filter select filter arg_intersection': 10,
                           'select project filter project arithmetic_subtraction': 5,
                           'select select list_subtraction project filter_a_where_b_is_max': 9,
                           'select filter project filter_a_where_b_is_compared_to project project': 7,
                           'select project project count arithmetic_subtraction': 5,
                           'select filter count filter count arithmetic_sum_multiple': 12,
                           'select minimum_number maximum_number project project date_subtraction': 8,
                           'select kth_highest kth_highest project project arithmetic_subtraction': 13,
                           'select select project filter project': 4,
                           'select arithmetic_mean_single select arithmetic_mean_single arg_minimum_number': 2,
                           'select select maximum_number project filter_a_where_b_is_compared_to project': 12,
                           'select project project arg_maximum_date': 2,
                           'select project filter filter list_subtraction project': 7,
                           'select project filter_a_where_b_is_compared_to project select list_subtraction': 10,
                           'select select select arithmetic_sum_multiple arg_minimum_number': 2,
                           'select kth_highest': 4,
                           'select select list_subtraction project filter_a_where_b_is_given_value project': 15,
                           'select select select filter filter arg_intersection': 8,
                           'select arithmetic_sum_single select arithmetic_subtraction arithmetic_subtraction': 9,
                           'select count select count arg_minimum_number': 2,
                           'select filter filter project project date_subtraction': 8,
                           'select select intersection project project union': 6,
                           'select filter project filter project arithmetic_subtraction': 6,
                           'select filter filter filter arg_intersection arg_intersection': 12,
                           'select project maximum_date project count': 6,
                           'select filter project minimum_number list_subtraction minimum_number': 7,
                           'select select arg_maximum_number': 2,
                           'select project grouped_count filter_a_where_b_is_compared_to project grouped_count': 4,
                           'select filter filter arithmetic_mean_single': 4,
                           'select filter list_subtraction arithmetic_sum_single': 8, 'boolean boolean logical_or': 3,
                           'select filter project count': 5, 'select project count': 5,
                           'select project select project date_subtraction': 7,
                           'select project project grouped_sum filter_a_where_b_is_compared_to project': 4,
                           'select project filter_a_where_b_is_compared_to project arithmetic_subtraction': 7,
                           'select project filter project filter_a_where_b_is_compared_to': 5,
                           'select select project intersection': 4,
                           'select select filter project filter_a_where_b_is_max': 4,
                           'select filter filter filter boolean': 6,
                           'select project project kth_lowest minimum_number arithmetic_subtraction': 11,
                           'select filter boolean boolean arg_bool': 5,
                           'select project filter project grouped_count arithmetic_sum_single': 4,
                           'select project count select arithmetic_subtraction': 6,
                           'select project select project filter_a_where_b_is_given_value project': 7,
                           'select project project project project arg_minimum_number': 2,
                           'select filter project grouped_count arithmetic_sum_single': 4,
                           'select filter filter arithmetic_sum_single arithmetic_sum_single arg_minimum_number': 2,
                           'select project filter_a_where_b_is_given_value boolean boolean arg_bool': 10,
                           'select arithmetic_sum_single select arithmetic_sum_single arithmetic_sum_multiple': 8,
                           'select project filter_a_where_b_is_compared_to project maximum_number': 12,
                           'select project arithmetic_division': 7,
                           'select project filter_a_where_b_is_compared_to filter': 5,
                           'select count project count arithmetic_subtraction': 4,
                           'select select arithmetic_subtraction arithmetic_division': 8,
                           'select project minimum_number list_subtraction minimum_number': 4,
                           'select project filter grouped_count project': 8,
                           'select filter filter project project arg_minimum_number': 2,
                           'select project filter minimum_number maximum_number arithmetic_subtraction': 4,
                           'select project filter filter_a_where_b_is_min': 2,
                           'select filter filter count count arg_maximum_number': 2,
                           'select filter project filter arg_intersection project': 6, 'select filter filter count': 5,
                           'select filter maximum_number list_subtraction maximum_number': 6,
                           'select project project filter_a_where_b_is_compared_to project grouped_sum': 4,
                           'select arithmetic_sum_single arithmetic_subtraction': 7,
                           'select boolean boolean boolean arg_bool': 5,
                           'select project project grouped_count filter_a_where_b_is_max project': 2,
                           'select filter filter filter arg_maximum_number': 10,
                           'select select project filter_a_where_b_is_compared_to filter': 4,
                           'select project filter project list_subtraction': 6, 'select filter project filter': 4,
                           'select select arithmetic_sum_single': 4,
                           'select project select filter_a_where_b_is_compared_to project filter_a_where_b_is_max': 22,
                           'select project grouped_count project project union': 8,
                           'select select select are_items_same are_items_same logical_and': 26,
                           'select arithmetic_sum_single select maximum_number arithmetic_subtraction': 14,
                           'select select minimum_number minimum_number arithmetic_sum_multiple': 6,
                           'select project arithmetic_mean_single': 4,
                           'select select arithmetic_sum_single count arithmetic_subtraction': 6,
                           'select project filter kth_highest filter_a_where_b_is_given_value': 7,
                           'select project arithmetic_sum_single boolean boolean arg_bool': 18,
                           'select project project project filter_a_where_b_is_compared_to': 4,
                           'select project project project arithmetic_sum_multiple arg_maximum_number': 15,
                           'select select project arithmetic_subtraction': 4,
                           'select maximum_number select minimum_number arithmetic_subtraction': 2,
                           'select select count compare_numbers compare_numbers arg_bool': 6,
                           'select filter project filter_a_where_b_is_compared_to count': 5,
                           'select filter project filter_a_where_b_is_given_value count': 5,
                           'select project grouped_mean filter_a_where_b_is_min': 2,
                           'select select project project arg_maximum_date': 2,
                           'select project filter_a_where_b_is_compared_to_date project arithmetic_sum_single': 5,
                           'select project project filter filter_a_where_b_is_compared_to arg_intersection': 12,
                           'select project select minimum_number filter_a_where_b_is_compared_to count': 14,
                           'select project select project filter_a_where_b_is_compared_to count': 6,
                           'select filter filter filter filter arg_intersection': 6,
                           'select project filter project filter_a_where_b_is_min project': 7,
                           'select filter filter arg_intersection filter project': 6,
                           'select project list_subtraction filter': 6,
                           'select project filter project select list_subtraction': 7,
                           'select project count project count arg_maximum_number': 10,
                           'select list_subtraction project filter_a_where_b_is_given_value': 13,
                           'select filter filter boolean': 5,
                           'select project grouped_count arithmetic_mean_single filter_a_where_b_is_compared_to count': 5,
                           'select filter filter project project arg_maximum_number': 2,
                           'select project filter project grouped_sum arithmetic_mean_single': 4,
                           'select select intersection count': 5,
                           'select filter project filter_a_where_b_is_given_value arg_intersection': 12,
                           'select project filter_a_where_b_is_given_value project project arithmetic_mean_single': 8,
                           'select project filter grouped_sum filter_a_where_b_is_min': 2,
                           'select arithmetic_sum_single select arithmetic_sum_single arg_maximum_number': 2,
                           'select project filter_a_where_b_is_given_value project filter_a_where_b_is_given_value project': 8,
                           'select project project grouped_count filter_a_where_b_is_compared_to': 6,
                           'select project grouped_count filter_a_where_b_is_max project project': 2,
                           'select project filter grouped_count filter_a_where_b_is_min': 2,
                           'select project project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to arg_intersection': 8,
                           'select filter filter filter filter union': 6,
                           'select project select count count arg_maximum_number': 4,
                           'select filter project filter_a_where_b_is_max list_subtraction filter_a_where_b_is_max': 6,
                           'select project project filter_a_where_b_is_compared_to project arithmetic_mean_single': 8,
                           'select filter filter project filter': 5,
                           'select filter filter project filter_a_where_b_is_min': 2,
                           'select project filter arithmetic_mean_single': 4,
                           'select project grouped_count filter_a_where_b_is_compared_to project grouped_mean': 4,
                           'select filter project grouped_count filter_a_where_b_is_min': 6,
                           'select count select count compare_numbers': 9,
                           'select project select project filter filter': 7,
                           'select select union select count arithmetic_subtraction': 9,
                           'select project list_subtraction filter project': 8,
                           'select project filter project filter_a_where_b_is_min': 2,
                           'select select select arg_minimum_number': 2,
                           'select project project grouped_mean filter_a_where_b_is_compared_to project': 4,
                           'select select count count arg_minimum_number': 2,
                           'select filter filter project filter_a_where_b_is_max': 2,
                           'select select project project intersection filter': 6,
                           'select filter filter project project arithmetic_subtraction': 8,
                           'select select project project union project': 4,
                           'select project filter boolean boolean arg_bool': 6,
                           'select project project union filter count': 6,
                           'select project filter project filter project': 6,
                           'select filter project grouped_count filter_a_where_b_is_compared_to': 6,
                           'select project filter grouped_count filter_a_where_b_is_max': 2,
                           'select select maximum_number maximum_number arg_maximum_number': 17,
                           'select project project filter_a_where_b_is_given_value filter': 6,
                           'select project project filter_a_where_b_is_compared_to filter': 4,
                           'select project project filter filter_a_where_b_is_min': 6,
                           'select filter project grouped_count filter_a_where_b_is_max project': 6,
                           'select project select filter count arithmetic_subtraction': 5,
                           'select project filter project grouped_sum arithmetic_sum_single': 4,
                           'select project project arithmetic_sum_single arithmetic_sum_single arithmetic_subtraction': 8,
                           'select filter project project filter count': 6,
                           'select project filter grouped_count filter_a_where_b_is_given_value': 7,
                           'select project project grouped_count filter_a_where_b_is_compared_to count': 6,
                           'select project grouped_count filter_a_where_b_is_compared_to list_subtraction project': 14,
                           'select project project filter_a_where_b_is_compared_to filter_a_where_b_is_compared_to count': 8,
                           'select project filter_a_where_b_is_given_value filter filter union': 11,
                           'select project project project filter_a_where_b_is_compared_to project': 6,
                           'select project filter grouped_count filter_a_where_b_is_max project': 4,
                           'select project filter project project filter': 6,
                           'select filter project project filter_a_where_b_is_compared_to project': 6,
                           'select minimum_number select maximum_number arithmetic_subtraction': 2}
